### ISSUE TITLE
about the libraries.properties: use on arm (cortex m4, but should be irrelevant)

### ISSUE THREAD

**Issue by jerabaul29** [stm32duino/ISM330DHCX#5]
I see on https://github.com/stm32duino/ISM330DHCX/blob/main/library.properties that:

https://github.com/stm32duino/ISM330DHCX/blob/10afb2658c9c50b4d3e950f6b92cb723344675b7/library.properties#L9

It looks to me like there is nothing that would say that this could not work on arm, right? Like, a cortex-m4f or similar, with an arduino core. If you confirm that it should work out I can test tonight. If it works, should arm be added to the list of architectures? :)

**Comment by cparata** [comment]
Hi @jerabaul29 ,
sure. the library is compliant with Arduino framework. If you cannot find some architectures supported, it is due because they were not tested. If you are able to test the library with other architectures and they work well, I suggest to submit a PR with an update of the library properties, so we can integrate it in the main repo.
Best Regards,
Carlo

**Comment by jerabaul29** [comment]
Sounds good. A bit delayed, but I hope to do it this weekend, if you have not heard back in a week or so just ping me :) .

**Comment by cparata** [comment]
I close this issue, because you can submit a PR to update the library properties
